export const PATIENT_BASE_PATH = '/patients';
export const PATIENT_DETAIL_PATH = '/patients/:id';
export const PATIENT_ENROLL_PATH = '/patients/enroll';
export const PATIENT_EDIT_PATH = '/patients/:id/edit';

export const PATIENT_LIST_STORAGE_KEY = 'htx_clinic_patient_list';
export const PATIENT_DETAIL_STORAGE_KEY = 'htx_clinic_patient_detail';
export const PATIENT_SEED_KEY = 'htx_clinic_patient_seeded_v4';

import type { PatientListItem } from '@/modules/patient/@types';

export const DUMMY_PATIENTS: PatientListItem[] = [
  {
    id: 'p-demo-01',
    mrn: 'MRN-00001',
    fullName: 'Eleanor Vance',
    dateOfBirth: '04/12/1965',
    gender: 'Female',
    email: 'eleanor.vance@healthmail.com',
    phone: '(312) 555-0101',
    pcpName: 'Dr. Marcus Reid',
    programs: ['APCM', 'RPM', 'BHI'],
    status: 'Active',
  },
  {
    id: 'p-demo-02',
    mrn: 'MRN-00002',
    fullName: 'James Harlow',
    dateOfBirth: '08/23/1978',
    gender: 'Male',
    email: 'james.harlow@healthmail.com',
    phone: '(415) 555-0182',
    pcpName: 'Dr. Susan Park',
    programs: ['APCM', 'RPM'],
    status: 'Active',
  },
  {
    id: 'p-demo-03',
    mrn: 'MRN-00003',
    fullName: 'Priya Nair',
    dateOfBirth: '11/30/1990',
    gender: 'Female',
    email: 'priya.nair@healthmail.com',
    phone: '(646) 555-0247',
    pcpName: 'Dr. Alan Cho',
    programs: ['APCM', 'BHI'],
    status: 'Pending',
  },
  {
    id: 'p-demo-04',
    mrn: 'MRN-00004',
    fullName: 'Robert Steele',
    dateOfBirth: '02/07/1955',
    gender: 'Male',
    email: 'robert.steele@healthmail.com',
    phone: '(213) 555-0394',
    pcpName: 'Dr. Marcus Reid',
    programs: ['APCM', 'RPM'],
    status: 'Active',
  },
  {
    id: 'p-demo-05',
    mrn: 'MRN-00005',
    fullName: 'Sofia Delgado',
    dateOfBirth: '06/18/1983',
    gender: 'Female',
    email: 'sofia.delgado@healthmail.com',
    phone: '(512) 555-0561',
    pcpName: 'Dr. Susan Park',
    programs: ['RPM'],
    status: 'Pending',
  },
  {
    id: 'p-demo-06',
    mrn: 'MRN-00006',
    fullName: 'David Kim',
    dateOfBirth: '09/14/1970',
    gender: 'Male',
    email: 'david.kim@healthmail.com',
    phone: '(718) 555-0638',
    pcpName: 'Dr. Alan Cho',
    programs: ['APCM', 'BHI'],
    status: 'Active',
  },
  {
    id: 'p-demo-07',
    mrn: 'MRN-00007',
    fullName: 'Angela Brooks',
    dateOfBirth: '03/25/1962',
    gender: 'Female',
    email: 'angela.brooks@healthmail.com',
    phone: '(404) 555-0712',
    pcpName: 'Dr. Marcus Reid',
    programs: ['APCM'],
    status: 'Active',
  },
  {
    id: 'p-demo-08',
    mrn: 'MRN-00008',
    fullName: 'Thomas Nguyen',
    dateOfBirth: '07/09/1988',
    gender: 'Male',
    email: 'thomas.nguyen@healthmail.com',
    phone: '(617) 555-0823',
    pcpName: 'Dr. Susan Park',
    programs: ['APCM', 'RPM', 'BHI'],
    status: 'Pending',
  },
  {
    id: 'p-demo-09',
    mrn: 'MRN-00009',
    fullName: 'Laura Simmons',
    dateOfBirth: '12/01/1975',
    gender: 'Female',
    email: 'laura.simmons@healthmail.com',
    phone: '(303) 555-0945',
    pcpName: 'Dr. Alan Cho',
    programs: ['APCM', 'RPM'],
    status: 'Active',
  },
  {
    id: 'p-demo-10',
    mrn: 'MRN-00010',
    fullName: 'Carlos Mendez',
    dateOfBirth: '05/16/1993',
    gender: 'Male',
    email: 'carlos.mendez@healthmail.com',
    phone: '(305) 555-1034',
    pcpName: 'Dr. Marcus Reid',
    programs: ['APCM'],
    status: 'Pending',
  },
  {
    id: 'p-demo-11',
    mrn: 'MRN-00011',
    fullName: 'Margaret Osei',
    dateOfBirth: '01/28/1958',
    gender: 'Female',
    email: 'margaret.osei@healthmail.com',
    phone: '(773) 555-1187',
    pcpName: 'Dr. Susan Park',
    programs: ['APCM', 'RPM', 'BHI'],
    status: 'Active',
  },
  {
    id: 'p-demo-12',
    mrn: 'MRN-00012',
    fullName: 'Kevin Walsh',
    dateOfBirth: '10/03/1981',
    gender: 'Male',
    email: 'kevin.walsh@healthmail.com',
    phone: '(614) 555-1256',
    pcpName: 'Dr. Alan Cho',
    programs: ['APCM', 'BHI'],
    status: 'Active',
  },
];
