import type { AppNotification } from './types';

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  // ── Patient Enrollment & Management ──────────────────────────────────────────
  {
    id: 'n-001',
    type: 'patient_enrolled',
    category: 'enrollment',
    title: 'New Patient Enrolled',
    message: 'Michael Thompson has been enrolled in the RPM program successfully.',
    timestamp: '2 min ago',
    read: false,
    actionPath: '/patients',
  },
  {
    id: 'n-002',
    type: 'patient_enrolled',
    category: 'enrollment',
    title: 'New Patient Enrolled',
    message: 'Sofia Martinez has been enrolled in the APCM program successfully.',
    timestamp: '18 min ago',
    read: false,
    actionPath: '/patients',
  },
  {
    id: 'n-003',
    type: 'patient_consent_received',
    category: 'enrollment',
    title: 'Consent Received',
    message: 'Emily Watson accepted the Terms of Service and is now an active patient.',
    timestamp: '45 min ago',
    read: false,
    actionPath: '/patients',
  },
  {
    id: 'n-004',
    type: 'patient_consent_received',
    category: 'enrollment',
    title: 'Consent Received',
    message: "James O'Brien accepted the Terms of Service and is now an active patient.",
    timestamp: '3 hr ago',
    read: true,
    actionPath: '/patients',
  },
  {
    id: 'n-005',
    type: 'ehr_import_completed',
    category: 'enrollment',
    title: 'EHR Import Completed',
    message: "James O'Brien's records have been successfully imported from Epic EHR.",
    timestamp: '1 hr ago',
    read: false,
    actionPath: '/patients',
  },
  {
    id: 'n-006',
    type: 'ehr_import_completed',
    category: 'enrollment',
    title: 'EHR Import Completed',
    message: "Emily Watson's records have been successfully imported from Epic EHR.",
    timestamp: '5 hr ago',
    read: true,
    actionPath: '/patients',
  },
  {
    id: 'n-007',
    type: 'ehr_import_completed',
    category: 'enrollment',
    title: 'EHR Import Completed',
    message: "Michael Thompson's records have been successfully imported from Epic EHR.",
    timestamp: '1 day ago',
    read: true,
    actionPath: '/patients',
  },

  // ── Staff & User Management ───────────────────────────────────────────────────
  {
    id: 'n-008',
    type: 'staff_invitation_sent',
    category: 'staff',
    title: 'Invitation Sent',
    message: 'An invitation has been sent to Dr. Sarah Kim (Cardiologist) to join the clinic.',
    timestamp: '30 min ago',
    read: false,
    actionPath: '/users',
  },
  {
    id: 'n-009',
    type: 'staff_invitation_sent',
    category: 'staff',
    title: 'Invitation Sent',
    message: 'An invitation has been sent to Nurse Rachel Green (RN) to join the clinic.',
    timestamp: '2 days ago',
    read: true,
    actionPath: '/users',
  },
  {
    id: 'n-010',
    type: 'staff_invitation_accepted',
    category: 'staff',
    title: 'Staff Member Joined',
    message: 'Dr. Michael Torres accepted their invitation and completed profile setup.',
    timestamp: '1 day ago',
    read: true,
    actionPath: '/users',
  },
  {
    id: 'n-011',
    type: 'staff_invitation_accepted',
    category: 'staff',
    title: 'Staff Member Joined',
    message: 'Nurse Rachel Green accepted their invitation and completed profile setup.',
    timestamp: '3 days ago',
    read: true,
    actionPath: '/users',
  },

  // ── Billing & Revenue ─────────────────────────────────────────────────────────
  {
    id: 'n-012',
    type: 'billing_report_ready',
    category: 'billing',
    title: 'Billing Report Ready',
    message: 'The May 2026 monthly billing report is ready. Total charges: $14,820.',
    timestamp: '2 hr ago',
    read: false,
    actionPath: '/billing',
  },
  {
    id: 'n-013',
    type: 'cpt_code_generated',
    category: 'billing',
    title: 'CPT Code Generated',
    message: 'CPT 99454 (device supply + daily recording) generated for Emily Watson.',
    timestamp: '4 hr ago',
    read: true,
    actionPath: '/billing',
  },
  {
    id: 'n-014',
    type: 'cpt_code_generated',
    category: 'billing',
    title: 'CPT Code Generated',
    message: 'CPT 99457 (remote monitoring — first 20 mins) generated for Michael Thompson.',
    timestamp: '1 day ago',
    read: true,
    actionPath: '/billing',
  },
];
