import type { UserListItem, UserType } from '../@types';

export const USER_BASE_PATH = '/users';
export const USER_DETAIL_PATH = '/users/:id';
export const USER_LIST_STORAGE_KEY = 'htx_clinic_user_list';
export const USER_SEED_KEY = 'htx_clinic_user_seeded';

export const USER_TYPE_OPTIONS: { value: UserType; label: string }[] = [
  { value: 'PHYSICIAN', label: 'Physician' },
  { value: 'NURSE', label: 'Registered Nurse' },
  { value: 'DHN', label: 'Digital Health Navigator' },
];

export const USER_TYPE_LABEL: Record<UserType, string> = {
  PHYSICIAN: 'Physician',
  NURSE: 'Registered Nurse',
  DHN: 'Digital Health Navigator',
};

export const DUMMY_USERS: UserListItem[] = [
  {
    id: 'u-demo-01',
    fullName: 'Dr. Marcus Reid',
    email: 'marcus.reid@clinic.com',
    phone: '(312) 555-0101',
    npiNumber: '1234567890',
    specialty: 'Cardiology',
    type: 'PHYSICIAN',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-02',
    fullName: 'Dr. Susan Park',
    email: 'susan.park@clinic.com',
    phone: '(415) 555-0182',
    npiNumber: '2345678901',
    specialty: 'Internal Medicine',
    type: 'PHYSICIAN',
    status: 'Active',
    addedBy: 'you',
  },
  {
    id: 'u-demo-03',
    fullName: 'Dr. Alan Cho',
    email: 'alan.cho@clinic.com',
    phone: '(646) 555-0247',
    npiNumber: '3456789012',
    specialty: 'Endocrinology',
    type: 'PHYSICIAN',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-04',
    fullName: 'Dr. Rachel Monroe',
    email: 'rachel.monroe@clinic.com',
    phone: '(213) 555-0394',
    npiNumber: '4567890123',
    specialty: 'Nephrology',
    type: 'PHYSICIAN',
    status: 'Pending',
    addedBy: 'you',
  },
  {
    id: 'u-demo-05',
    fullName: 'Dr. James Okafor',
    email: 'james.okafor@clinic.com',
    phone: '(512) 555-0561',
    npiNumber: '5678901234',
    specialty: 'Pulmonology',
    type: 'PHYSICIAN',
    status: 'Deactivated',
    addedBy: 'superadmin',
    deactivatedOn: '03/15/2025',
  },
  {
    id: 'u-demo-06',
    fullName: 'Sarah Thompson',
    email: 'sarah.thompson@clinic.com',
    phone: '(718) 555-0638',
    npiNumber: '6789012345',
    specialty: 'General',
    type: 'NURSE',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-07',
    fullName: 'Michael Torres',
    email: 'michael.torres@clinic.com',
    phone: '(404) 555-0712',
    npiNumber: '7890123456',
    specialty: 'General',
    type: 'NURSE',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-08',
    fullName: 'Linda Watson',
    email: 'linda.watson@clinic.com',
    phone: '(617) 555-0823',
    npiNumber: '8901234567',
    specialty: 'General',
    type: 'NURSE',
    status: 'Pending',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-09',
    fullName: 'Kevin Patel',
    email: 'kevin.patel@clinic.com',
    phone: '(303) 555-0945',
    npiNumber: '9012345678',
    specialty: 'General',
    type: 'NURSE',
    status: 'Deactivated',
    addedBy: 'superadmin',
    deactivatedOn: '02/08/2025',
  },
  {
    id: 'u-demo-10',
    fullName: 'Amara Osei',
    email: 'amara.osei@clinic.com',
    phone: '(305) 555-1034',
    npiNumber: '0123456789',
    specialty: 'N/A',
    type: 'DHN',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-11',
    fullName: 'Derek Liu',
    email: 'derek.liu@clinic.com',
    phone: '(773) 555-1187',
    npiNumber: '1122334455',
    specialty: 'N/A',
    type: 'DHN',
    status: 'Active',
    addedBy: 'superadmin',
  },
  {
    id: 'u-demo-12',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@clinic.com',
    phone: '(614) 555-1256',
    npiNumber: '2233445566',
    specialty: 'N/A',
    type: 'DHN',
    status: 'Pending',
    addedBy: 'superadmin',
  },
];
